#!/usr/bin/env bash
#
# Simple script to parse df and look for partitons
# over a specific percentage
#
# Author: Dave Eddy <dave@daveeddy.com>

# Percentage to print on
threshold=90

df -h
ret=0
while read filesystem size used avail perc_use mount; do
	if ((${perc_use//%/} >= $threshold)); then
		echo "$filesystem ($mount) $perc_use";
		ret=1
	fi;
done < <(df -hP)
exit "$ret"
