#!/usr/bin/env bash
#
# prompt from the show LOST
# the code has been hashed
#
# Author: Dave Eddy <dave@daveeddy.com>

trap true 1 2 3 4 5 6 7 8 15
code='1b62110df55087077ddbaa840a3edf63'
while [[ "$pass" != "$code" ]]; do
        clear
	echo -ne "\e[0;32m"
        read  -p ">: " line
        pass=$(openssl md5 <<< "$line")
done
